# -*- coding: utf-8 -*-
from pathlib import Path

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMessageBox

import configurador
from generador_ss import generar_archivos_ss, FormatoLayoutExcelException


# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


class Ui_MainWindow(object):
    def __init__(self):
        if not Path('settings.ini').is_file():
            configurador.generate_config()

        config = configurador.read_config()
        self.fname = ''

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(366, 308)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 321, 191))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(15, 0, 15, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_fecha = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_fecha.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fecha.setObjectName("label_fecha")
        self.verticalLayout_2.addWidget(self.label_fecha)
        self.qna_proc_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.qna_proc_edit.setObjectName("qna_proc_edit")
        self.verticalLayout_2.addWidget(self.qna_proc_edit)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.botonArchivo = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.botonArchivo.setFont(font)
        self.botonArchivo.setDefault(False)
        self.botonArchivo.setFlat(False)
        self.botonArchivo.setObjectName("botonArchivo")
        self.verticalLayout_2.addWidget(self.botonArchivo)
        self.dirArchivo = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.dirArchivo.setText("")
        self.dirArchivo.setTextFormat(QtCore.Qt.PlainText)
        self.dirArchivo.setAlignment(QtCore.Qt.AlignCenter)
        self.dirArchivo.setWordWrap(True)
        self.dirArchivo.setObjectName("dirArchivo")
        self.verticalLayout_2.addWidget(self.dirArchivo)
        self.generarSS = QtWidgets.QPushButton(self.centralwidget)
        self.generarSS.setGeometry(QtCore.QRect(90, 260, 158, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.generarSS.setFont(font)
        self.generarSS.setObjectName("generarSS")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.botonArchivo.clicked.connect(self.buscar_archivo)
        self.generarSS.clicked.connect(self.generar_ss)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_fecha.setText(_translate("MainWindow", "Quincena de proceso:"))
        self.label.setText(_translate("MainWindow", "Seleccione archivo:"))
        self.botonArchivo.setText(_translate("MainWindow", "Archivo"))
        self.generarSS.setText(_translate("MainWindow", "Generar Archivos"))

    def buscar_archivo(self):
        self.fname = QFileDialog.getOpenFileName(self.centralwidget, "Abrir archivo", "",
                                                 "Archivos Excel (*.xlsx)")
        self.dirArchivo.setText(self.fname[0])

    def generar_ss(self):
        if self.qna_proc_edit.text() == '':
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText('Sin número de quincena')
            msg.setInformativeText('No se puede generar el concepto SS sin número de quincena\n'
                                   'favor de introducir la quincena en el formato aaaaqq')
            msg.setWindowTitle('Sin número de quincena')
            msg.exec_()
        elif self.fname == '':
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText('Sin archivo a procesar')
            msg.setInformativeText('No se puede generar el concepto SS sin el archivo de relación\n'
                                   'seleccione el archivo con la relación de trabajadores para generar SS.')
            msg.setWindowTitle('Sin número de quincena')
            msg.exec_()
        else:
            try:
                generar_archivos_ss(int(self.qna_proc_edit.text()), self.fname[0])
            except FormatoLayoutExcelException as e:
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Critical)
                msg.setText("Error")
                msg.setInformativeText(f'ocurrió un error: {e.message}\n'
                                       f'{e.__class__}')
                msg.setWindowTitle("Error")
                msg.exec_()
            except ValueError as e:
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText('Número de quincena incorrecto')
                msg.setInformativeText('No se puede generar el concepto SS sin número de quincena\n'
                                       'favor de introducir la quincena en el formato aaaaqq')
                msg.setWindowTitle('Número de quincena incorrecto')
                msg.exec_()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
